version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chatapp-backend
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    command: npm start
    networks:
      - chatapp-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chatapp-frontend
    restart: always
    ports:
      - "4173:4173"
    environment:
      - REACT_APP_API_URL=http://backend:5001
    volumes:
      - ./frontend:/app
    command: npm run preview
    networks:
      - chatapp-network

networks:
  chatapp-network:
    driver: bridge

volumes:
  backend_node_modules:
  frontend_node_modules:
